### PR TITLE
Add database core. Not usable yet.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Synapz1** [comment]
It needs to store the whole warnings.yml file. Maybe whenever someone makes or deletes a warning it syncs warning file then deletes it? Or just syncs it all every X minutes

**Comment by ghost** [comment]
Should sync only when it needs to. So i guess whenever a warning is created/deleted.

**Comment by ghost** [comment]
offline message storing done, player receives message upon login.

**Comment by ghost** [comment]
You can pull for now while i work on MySQL in the mean time.

**Pull request merged**
